services:
  db_user:
    image: postgres
    container_name: db_user
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: user_service_db
    ports:
      - "5433:5432"
    volumes:
      - db-user:/var/lib/postgresql
    networks:
      SD_Network:

  userservice:
    build:
      context: ./UserService
      dockerfile: ./Dockerfile
    container_name: userservice
    ports:
      - "8091:8081"
    environment:
      - DB_IP=db_user
      - DB_PORT=5432
      - DB_DBNAME=user_service_db
      - DB_USER=postgres
      - DB_PASSWORD=root
    networks:
      SD_Network:

  db_device:
    image: postgres
    container_name: db_device
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: device_service_db
    ports:
      - "5434:5432"
    volumes:
      - db-device:/var/lib/postgresql
    networks:
      SD_Network:

  deviceservice:
    build:
      context: ./DeviceService
      dockerfile: ./Dockerfile
    container_name: deviceservice
    ports:
      - "8092:8082"
    environment:
      - DB_IP=db_device
      - DB_PORT=5432
      - DB_DBNAME=device_service_db
      - DB_USER=postgres
      - DB_PASSWORD=root
    networks:
      SD_Network: 

  db_authentication:
    image: postgres
    container_name: db_authentication
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: authentication_service_db
    ports:
      - "5435:5432"
    volumes:
      - db-authentication:/var/lib/postgresql
    networks:
      SD_Network:

  authenticationservice:
    build:
      context: ./AuthenticationService
      dockerfile: ./Dockerfile
    container_name: authenticationservice
    ports:
      - "8093:8083"
    environment:
      - DB_IP=db_authentication
      - DB_PORT=5432
      - DB_DBNAME=authentication_service_db
      - DB_USER=postgres
      - DB_PASSWORD=root
    networks:
      SD_Network:

  db_monitoring:
    image: postgres
    container_name: db_monitoring
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: monitoring_service_db
    ports:
      - "5436:5432"
    volumes:
      - db-monitoring:/var/lib/postgresql
    networks:
      SD_Network:

  monitoringservice:
    build:
      context: ./MonitoringService
      dockerfile: ./Dockerfile
    container_name: monitoringservice
    ports:
      - "8094:8084"
    environment:
      - DB_IP=db_monitoring
      - DB_PORT=5432
      - DB_DBNAME=monitoring_service_db
      - DB_USER=postgres
      - DB_PASSWORD=root
    networks:
      SD_Network:

  frontend:
    build:
      context: ./frontend 
      dockerfile: ./Dockerfile
    container_name: frontend
    restart: always
    networks:
      - SD_Network

  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: always
    ports:
      - "81:80" 
      - "8081:8080" 
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" 
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./dynamic:/etc/traefik/dynamic:ro" 
      - "./logs:/var/log/traefik"
    develop: 
      watch:
       - path: ./dynamic                  
         action: restart
    networks:
      SD_Network:   

volumes:
  db-user:
  db-device:
  db-authentication:
  db-monitoring:

networks:
  SD_Network:
    external: true
